### ISSUE TITLE
No such file when fine tuning GAN

### ISSUE THREAD

**Issue by ithinco** [yiranran/Audio-driven-TalkingFace-HeadPose#18]
```
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/memory_seq_p2p/60_net_G.pth'
```

**Comment by shreyanshdas00** [comment]
> ```
> FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/memory_seq_p2p/60_net_G.pth'
> ```

Hi could you let me know how you solved the error?
