### ISSUE TITLE
我在安装环境时碰到了问题，ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by dmdomo** [yiranran/Audio-driven-TalkingFace-HeadPose#19]

**Comment by wangzheliu** [comment]
你好。你的tensorflow和bazel版本是什么，当我运行./runtests.sh时，出现了下面错误
ERROR: /home/liu@no3/3Dface/Deep3DFaceReconstruction/tf_mesh_renderer/mesh_renderer/kernels/BUILD:7:1: error loading package '@com_google_googletest//': Extension file not found. Unable to load package for '@rules_cc//cc:defs.bzl': The repository could not be resolved and referenced by '//mesh_renderer/kernels:rasterize_triangles_impl_test'.
ERROR: Analysis of target '//mesh_renderer/kernels:rasterize_triangles_impl_test' failed; build aborted.
INFO: Elapsed time: 0.118s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by dmdomo** [comment]
你好，我的tensorflow是1.14.0，我不知道bazel是什么，我猜你说的是blaze，我的blaze版本是0.11.3
因为我也是新手，不能解答你的问题，抱歉。
