### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/yugaljain03/audio_face_animation/audio_driven_headpose/Audio-driven-TalkingFace-HeadPose/render-to-video/../Deep3DFaceReconstruction/output/render/19_news/33/bm/frame18_renderold_bm.png'

### ISSUE THREAD

**Issue by yugaljain1999** [yiranran/Audio-driven-TalkingFace-HeadPose#57]
@yiranran I am unable to find `rederold_bm.png` files in `bm` folder. What script I should run to generate these files?
Please help me to solve this.. 

PS - II am running demo colab file which is mentioned in README and I already installed octave as per given instructions in demo colab link in Readme..
Thanks

**Comment by jordanfranklin1** [comment]
May I ask if you were able to run the model successfully?

**Comment by yugaljain1999** [comment]
Yeah I successfully generated those png files by runing `pkg load image` command in octave command prompt.
Still I am getting CUDA out of memory error while running finetuning GAN python file for 60 epochs..
@yiranran @jordanfranklin1 Do you know what parameters should I change to get rid of this error?
Thanks

**Comment by jordanfranklin1** [comment]
@yugaljain1999 unfortunately I do not know which. I am actually having issues with running the 3D face reconstruction portion of the Colab demo. If you were able to get that part running, do you mind showing me how you got it to work?

**Comment by yugaljain1999** [comment]
Yeah sure.. just run octave --eval `pkg load image` command in colab to solve this issue.

**Comment by jordanfranklin1** [comment]
I tried that and it didn't work. However thanks for the response.

**Comment by VERMANs** [comment]
> 我试过了，但没有用。不过感谢您的回复。

may you tell the version of octave?perhaps 'image' cant support octave5.2.0  

use ''apt list --installed|grep octave'' to watch version
